### ISSUE TITLE
Publish new release with placeholder included

### ISSUE THREAD

**Issue by artstalker** [bitExpert/ng2-combobox#21]
Hi,

I see you've added placeholder support to the combobox. But we cannot reuse this functionality because latest version is still 0.5.4

**Comment by shochdoerfer** [comment]
The original plan was to merge the other open PRs before creating a new release. Since that might take a while we could create a new release in the next couple of days. Would that work for you?

**Comment by artstalker** [comment]
We fixed that issues by adding the code right into node_modules source code. So it's not very urgent at this moment. We can wait until you do major release.

**Comment by shochdoerfer** [comment]
@artstalker we just released version 0.6.0. Please have a look and give feedback in case of problems.
