### ISSUE TITLE
Implicit 'any' type

### ISSUE THREAD

**Issue by duffbuster** [bitExpert/ng2-combobox#30]
`TS7008: Member '_input' implicitly has an 'any' type.`

This can be solved by simply typing the `_input` viewchild as `any`.

**Comment by shochdoerfer** [comment]
Mind providing a PR? ;)

**Comment by duffbuster** [comment]
https://github.com/bitExpert/ng2-combobox/pull/31

**Comment by shochdoerfer** [comment]
Thank you!
