### ISSUE TITLE
Can I use ng2-combobox with custom value?

### ISSUE THREAD

**Issue by rovico** [bitExpert/ng2-combobox#34]
In my project i need a combobox field, in that user can select pre-defined or type custom values.

I tried with ng2-combobox, but seems it doesn't provide feature that i need.

How i try to use it:

```
<pre>
   <combo-box [listData]="comboConstants"
                        [displayField]="'text'"
                        [valueField]="'id'"
                        [(ngModel)]="rule.value"
                        [ngModelOptions]="{standalone: true}"
                        [forceSelection]="false"
                        [inputClass]="'form-control mt-2'"
                        [clearOnSelect]="false"
                        (onInitValue)="initComboBoxValue($event)"></combo-box>
</pre>
```

When i setted forceSelection to false i expected that combobox will set value that i typed in input to rule.value, but it doesn't. (rule.value become undefined)

May be i'm doing something wrong... But i think, it would be a nice feature - a possibility to type custom values...

Best regards!

**Comment by shochdoerfer** [comment]
Feel free to contribute this as a new feature, we are open for PRs ;)

**Comment by rovico** [comment]
Ok. I did something in my fork. I will test the functionality of component with my changes and then i'll make pull-request if all works fine
