### ISSUE TITLE
rxjs/rx no longer needed

### ISSUE THREAD

**Issue by SuperVillainPresident** [bitExpert/ng2-combobox#36]
When I install the component, I'm getting these errors:

 Module '".../node_modules/rxjs/Rx"' has no exported member 'Observable'.
node_modules/ng2-combobox/src/combo-box.component.ts(2,21): error TS2305: Module '".../node_modules/rxjs/Rx"' has no exported member 'Subscription'.

In the code you have import { Observable, Subscription} from 'rxjs/Rx';.
As of Angular 6, it needs to be just ...from 'rxjs';

**Comment by shochdoerfer** [comment]
Mind providing a PR for us?

**Comment by SuperVillainPresident** [comment]
Fixed with PR #39 

This is my first PR, so I hope I got it right.
