### ISSUE TITLE
Implement a style API for consumers

### ISSUE THREAD

**Issue by MidiDEVS** [bitExpert/ng2-combobox#5]
Heya,

combo-box could use a style API that let consumers of combo-box apply styles to local-DOM elements of combo-box.

I only know [how to do this with ](https://www.polymer-project.org/1.0/docs/devguide/styling#custom-css-mixins)polymer, not with angular.
But there should be an angular way to implement a style APIs as well.

Examle Problem for this issue:
Implementing combo-box with the intend to style it's input color red when some conditions are met.

**Comment by MidiDEVS** [comment]
Currently possible component **consumer** workaround:

apply the shadow piercing selector on the combo-box selector, for a css rule.
    
this styles inputs inside the local dom of combo-box

```
        combo-box.condition::shadow input {
         color: red;
        }
```

this styles all inputs behind all occuring shadow-boundries behind combo box.
Depricated in chrome.

```
        combo-box.condition /deep/ input {
         color: red;
        }
```

NOTE:
These mentioned workarounds collide with the intend of shadow-DOM and webcomponents,
since we pierce encapsulation.

**Comment by MidiDEVS** [comment]
[Interesting toppical (jan/17) post on this](http://stackoverflow.com/questions/41677947/why-does-css-styles-not-apply-on-angular-2-component-with-vaadin-elements?answertab=votes#tab-top)

**Comment by MidiDEVS** [comment]
@phillipgrimm

When implementing the `inputClass` style API approach, i think you got consumer-styling of the internal input working somehow.
This should only be possible when configuring your angular app's [view-encapsulation](https://angular-2-training-book.rangle.io/handout/advanced-components/view_encapsulation.html) to `emulated`
or `none`.

If so, this is an important detail for component-consumers.

**Comment by MidiDEVS** [comment]
Found [Angular's way to provide 'style-APIs'](http://blog.angular-university.io/how-to-create-an-angular-2-library-and-how-to-consume-it-jspm-vs-webpack/).

This also depends on the view-encapsulation configuration. It must be at least `Emulated` (a [shady-DOM](http://stackoverflow.com/questions/37691135/whats-the-difference-between-polymers-shady-dom-vs-shadow-dom?answertab=votes#tab-top) equivalent).

**Comment by shochdoerfer** [comment]
Feel free to create a PR with the changes and we will review it.
